version: '{build}'
install:
	- cmd: windows\install.bat
build: off
test: off
deploy: off
notifications:
	- provider: Email
		on_build_success: true
		on_build_failure: true
		on_build_status_changed: true
		to:
			- rouslan.solomakhin@gmail.com
