#!/bin/bash
#
# Copyright 2015 Rouslan Solomakhin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FORMAT="\"%C\": %E"
COMMAND="$EMACS"
if [ -z "$COMMAND" ]; then
  COMMAND="emacs --no-site-file"
fi

for i in `seq 1 10`; do
  /usr/bin/time -f "$FORMAT" $COMMAND --kill
done

for i in `seq 1 10`; do
  /usr/bin/time -f "$FORMAT" $COMMAND ~/.emacs.d/init.el --kill
done

for i in `seq 1 10`; do
  /usr/bin/time -f "$FORMAT" $COMMAND ~/chrome/src/base/strings/string16.cc --kill
done
