#!/bin/bash
#
# Copyright 2015 Rouslan Solomakhin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

for file in `git ls-files`; do
  if [ "$file" == "appveyor.yml" ]; then continue; fi
  if [ "$file" == "fonts/LICENCE.txt" ]; then continue; fi
  if [ "$file" == "fonts/README.rst" ]; then continue; fi
  if [ "$file" == "install" ]; then continue; fi
  if [ "$file" == "LICENSE" ]; then continue; fi
  if [ "$file" == "README.md" ]; then continue; fi
  if [ "$file" == ".travis.yml" ]; then continue; fi
  if [ "$file" == "windows/env.bat" ]; then continue; fi
  if [ "$file" == "windows/install.bat" ]; then continue; fi
  mkdir -pv ~/.`dirname $file`
  ln --symbolic --force --verbose --no-target-directory ~/.dotfiles/$file ~/.$file
done

for file in ~/.vim/pack/rsolomakhin/start/*; do
  if [ -e $file/doc ]; then vim -u NONE -c "helptags $file/doc" -c q; fi
done
