#!/bin/bash
#
# Copyright 2016 Rouslan Solomakhin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

die() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
  exit 1
}

export HOME=/tmp/rsolomakhin-dotfiles-test-home
rm -rf $HOME || die "Cannot remove the $HOME dir"
mkdir -pv $HOME || die "Cannot create $HOME dir"

pushd $(dirname ${BASH_SOURCE[0]}) || die "Cannot go into ${BASH_SOURCE[0]} dir"

./install || die "Unable to perform a clean install"
./install || die "Unable to perform a quick install check"
./install --force || die "Unable to force re-install"
echo ALL TESTS PASS
