" Copyright 2015 Rouslan Solomakhin
"
" Licensed under the Apache License, Version 2.0 (the "License");
" you may not use this file except in compliance with the License.
" You may obtain a copy of the License at
"
"     http://www.apache.org/licenses/LICENSE-2.0
"
" Unless required by applicable law or agreed to in writing, software
" distributed under the License is distributed on an "AS IS" BASIS,
" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
" See the License for the specific language governing permissions and
" limitations under the License.

let &colorcolumn='+' . join(range(1, 1), ',+')
set autoindent
set backspace=indent,eol,start
set completeopt=
set encoding=utf-8
set expandtab
set guioptions=
set hidden
set ignorecase
set incsearch
set laststatus=2
set mouse=
set nocompatible
set nocursorline
set nojoinspaces
set nonumber
set nospell
set ruler
set shiftwidth=2
set showcmd
set smartcase
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set timeout
set timeoutlen=1000
set ttimeoutlen=0
set viminfo='100,<100,:100,s100,h,%,n~/.viminfo
set wildmenu

imap <C-A> <Esc>I
imap <C-E> <Esc>A

if $TERM == "xterm"
  set t_Co=256
endif

if has("win32")
  set spellfile=~/vimfiles/spell/en.utf-8.add
  set directory=~/vimfiles/swap,.
  set guifont=Consolas:h11:cANSI
else
  set spellfile=~/.vim/spell/en.utf-8.add
  set directory=~/.vim/swap,.
  set guifont=Ubuntu\ Mono\ 12
endif

silent! if plug#begin()
  if !has("win32") && !has("win32unix") && v:version >=703 && has("patch584")
    Plug 'Valloric/YouCompleteMe',
          \ {'do': './install.sh --clang-completer --gocode-completer'}
    let g:ycm_global_ycm_extra_conf =
          \ expand('~/chrome/src/tools/vim/chromium.ycm_extra_conf.py')
    let g:ycm_always_populate_location_list = 1
  endif

  if !has("win32")
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
    nnoremap <buffer><silent> <leader>t :FZF<CR>
  endif

  " <leader>= - format selected lines or current line.
  " <leader>b - format buffer.
  Plug 'google/vim-maktaba' | Plug 'google/vim-glaive' |
        \ Plug 'google/vim-codefmt'

  " Colorschemes
  " Plug 'altercation/vim-colors-solarized'
  " Plug 'jnurmine/Zenburn'
  " Plug 'nanotech/jellybeans.vim'
  " Plug 'sjl/badwolf'
  Plug 'w0ng/vim-hybrid'

  Plug 'tpope/vim-dispatch'
  Plug 'tpope/vim-fugitive'

  " ]q - next quickfix.
  " [q - previous quickfix.
  Plug 'tpope/vim-unimpaired'

  " <leader>q - show/hide quickfix list.
  " <leader>l - show/hide location list.
  Plug 'Valloric/ListToggle'

  call plug#end()
endif

" vim-codefmt
try
  call glaive#Install()
  Glaive codefmt plugin[mappings]
catch
endtry

" Colorscheme
try
  if !empty($XTERM_VERSION) || !empty($ITERM_PROFILE)
    let g:hybrid_use_Xresources=1
    set background=dark
  endif
  colorscheme hybrid
catch
endtry

" vim-fugitive
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

let g:EclimCompletionMethod = 'omnifunc'

command! ChromiumSource :Start x-www-browser
      \ https://code.google.com/p/chromium/codesearch\#chromium/src/%

if filereadable(glob("~/chrome/src/tools/vim/ninja-build.vim"))
  source ~/chrome/src/tools/vim/ninja-build.vim
endif

augroup custom
  autocmd!
  autocmd BufRead,BufNewFile DEPS set filetype=python
  autocmd BufRead,BufNewFile *.gypi set filetype=python
  autocmd BufRead,BufNewFile *.gyp  set filetype=python
  autocmd BufRead,BufNewFile /tmp/cl_description* set filetype=gitcommit

  autocmd FileType cpp,c,html,javascript,sh,zsh,vim,python,go
        \ setlocal textwidth=80
  autocmd FileType cpp nnoremap <buffer><silent> <C-]> :YcmCompleter GoTo<CR>
  autocmd FileType cpp setlocal cinoptions=N-s,g.5s,h.5s
  autocmd FileType gitcommit setlocal spell
  autocmd FileType gitcommit setlocal textwidth=72
  autocmd FileType java let b:codefmt_formatter = 'clang-format'
  autocmd FileType java setlocal shiftwidth=4
  autocmd FileType java setlocal softtabstop=4
  autocmd FileType java setlocal tabstop=4
  autocmd FileType java setlocal textwidth=100

  autocmd BufNewFile,BufRead */WebKit/* setlocal shiftwidth=4
  autocmd BufNewFile,BufRead */WebKit/* setlocal softtabstop=4
  autocmd BufNewFile,BufRead */WebKit/* setlocal tabstop=4
  autocmd BufNewFile,BufRead */WebKit/* setlocal textwidth&

  autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup end

" Must be after augroup, because has its own autocmds.
if filereadable(glob("~/chrome/src/tools/vim/mojom/syntax/mojom.vim"))
  set runtimepath^=~/chrome/src/tools/vim/mojom
endif
