" Copyright 2015 Rouslan Solomakhin
"
" Licensed under the Apache License, Version 2.0 (the "License");
" you may not use this file except in compliance with the License.
" You may obtain a copy of the License at
"
"     http://www.apache.org/licenses/LICENSE-2.0
"
" Unless required by applicable law or agreed to in writing, software
" distributed under the License is distributed on an "AS IS" BASIS,
" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
" See the License for the specific language governing permissions and
" limitations under the License.

filetype plugin indent on
set autoindent
set backspace=indent,eol,start
set colorcolumn=+1
set encoding=utf-8
set expandtab
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set nocompatible
set nojoinspaces
set ruler
set shiftwidth=2
set showcmd
set showmode
set smartcase
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set textwidth=80
set wildmenu
syntax on
hi ColorColumn ctermbg=gray

au BufNewFile,BufRead */WebKit/*
      \ setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth&

au BufReadPost *
      \ call setpos(".", getpos("'\""))

if has("win32")
  set viminfo='10,\"100,:20,%,n~/_viminfo
else
  set viminfo='10,\"100,:20,%,n~/.viminfo
endif

if isdirectory(expand('~/chrome'))
  source ~/chrome/src/tools/vim/clang-format.vim
  source ~/chrome/src/tools/vim/filetypes.vim
  source ~/chrome/src/tools/vim/ninja-build.vim
endif

if isdirectory(expand('~/.fzf'))
  set rtp+=~/.fzf
endif
