" Copyright 2015 Rouslan Solomakhin
"
" Licensed under the Apache License, Version 2.0 (the "License");
" you may not use this file except in compliance with the License.
" You may obtain a copy of the License at
"
"     http://www.apache.org/licenses/LICENSE-2.0
"
" Unless required by applicable law or agreed to in writing, software
" distributed under the License is distributed on an "AS IS" BASIS,
" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
" See the License for the specific language governing permissions and
" limitations under the License.

silent! if plug#begin('~/.vim/plugged')
  Plug 'junegunn/fzf', {
        \ 'dir': '~/.fzf',
        \ 'do': 'yes \| ./install',
        \ 'on': 'FZF' }
  Plug 'junegunn/vim-oblique'
  Plug 'junegunn/vim-peekaboo'
  Plug 'junegunn/vim-pseudocl'
  Plug 'tpope/vim-fugitive'
  Plug 'Valloric/YouCompleteMe', {
        \ 'do': './install.sh --clang-completer',
        \ 'for': ['c', 'cpp'] }
  call plug#end()
endif

hi ColorColumn ctermbg=gray
set autoindent
set backspace=indent,eol,start
set colorcolumn=+1
set encoding=utf-8
set expandtab
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set nocompatible
set nojoinspaces
set ruler
set shiftwidth=2
set showcmd
set showmode
set smartcase
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set textwidth=80
set wildmenu

au BufNewFile,BufRead */WebKit/*
      \ setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth&

au BufReadPost *
      \ call setpos(".", getpos("'\""))

if has("win32")
  set viminfo='10,\"100,:20,%,n~/_viminfo
else
  set viminfo='10,\"100,:20,%,n~/.viminfo
endif

if isdirectory(expand('~/chrome'))
  source ~/chrome/src/tools/vim/clang-format.vim
  source ~/chrome/src/tools/vim/filetypes.vim
  source ~/chrome/src/tools/vim/ninja-build.vim
  let g:ycm_global_ycm_extra_conf =
        \ expand('~/chrome/src/tools/vim/chromium.ycm_extra_conf.py')
endif
