;; -*- lisp -*-
;;
;; Copyright 2015 Rouslan Solomakhin
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.

(source melpa)

(depends-on "clang-format")
(depends-on "company")
(depends-on "google-c-style")
(depends-on "magit")
(depends-on "pallet")
(depends-on "protobuf-mode")
(depends-on "smartparens")
(depends-on "volatile-highlights")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
