# Copyright 2015 Rouslan Solomakhin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case $- in
  *i*)      ;;
  *) return ;;
esac

source ~/.common.sh

source_if_exists "$HOME/.fzf.bash"
source_if_exists "$HOME/google-cloud-sdk/completion.bash.inc"
source_if_exists "$HOME/google-cloud-sdk/path.bash.inc"
source_if_exists "/etc/bash_completion"
source_if_exists "/usr/local/git/current/share/git-core/git-completion.bash"
source_if_exists "/usr/local/git/current/share/git-core/git-prompt.sh"

if command -v brew >/dev/null 2>&1; then
  BREW_PREFIX=$(brew --prefix)
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/brew"
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/cargo"
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/git-completion.bash"
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/git-prompt.sh"
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/npm"
  source_if_exists "$BREW_PREFIX/etc/bash_completion.d/tmux"
fi

# Default PS1 theme.
# \[\e[5 q\] resets the cursor to a blinking bar.
if command -v __git_ps1 >/dev/null 2>&1; then
  export PS1='\[\e[5 q\][\[\e[32m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\w]\[\e[34m\]$(__git_ps1 \(%s\))\[\e[m\]\$ '
else
  export PS1='\[\e[5 q\][\[\e[32m\]\u\[\e[m\]@\[\e[34m\]\h\[\e[m\]:\w]\$ '
fi

# Silence the warning the default interactive shell is now zsh.
export BASH_SILENCE_DEPRECATION_WARNING=1

# vi:ft=sh
