name: Windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v6
      - name: Run Windows installation test
        run: windows\test.bat
